--
-- PostgreSQL database dump
--

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2023-05-30 13:59:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 16399)
-- Name: cart; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cart (
    id integer NOT NULL,
    user_id integer NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.cart OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16402)
-- Name: cart_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16403)
-- Name: order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."order" (
    id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp without time zone NOT NULL,
    status character varying(32) DEFAULT 'создан'::character varying NOT NULL
);


ALTER TABLE public."order" OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16407)
-- Name: order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."order" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16408)
-- Name: orders_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_products (
    order_id integer NOT NULL,
    product_id integer NOT NULL
);


ALTER TABLE public.orders_products OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16411)
-- Name: product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product (
    id integer NOT NULL,
    file_name character varying(256) NOT NULL,
    file_path character varying(256) NOT NULL,
    file_type character varying(32) NOT NULL,
    file_size bigint NOT NULL,
    title character varying(256) NOT NULL,
    price numeric(10,2) NOT NULL,
    description character varying(512) DEFAULT ''::character varying NOT NULL
);


ALTER TABLE public.product OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16417)
-- Name: product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16418)
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    username character varying(256) NOT NULL,
    password character varying(60) NOT NULL,
    role character varying(10) NOT NULL
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16421)
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3357 (class 0 OID 16399)
-- Dependencies: 214
-- Data for Name: cart; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3359 (class 0 OID 16403)
-- Dependencies: 216
-- Data for Name: order; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."order" (id, user_id, created_at, status) VALUES (1, 1, '2023-05-27 17:30:02.831569', 'создан');


--
-- TOC entry 3361 (class 0 OID 16408)
-- Dependencies: 218
-- Data for Name: orders_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.orders_products (order_id, product_id) VALUES (1, 1);


--
-- TOC entry 3362 (class 0 OID 16411)
-- Dependencies: 219
-- Data for Name: product; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product (id, file_name, file_path, file_type, file_size, title, price, description) VALUES (1, '20042009bb2.jpg', 'C:\Users\minya\Documents\Code\Java\attestation-spring-app\uploads\images\20042009bb2.jpg', 'image/jpeg', 123792, 'Кофемашина Krups Roma Black EA810870', 36999.00, 'Krups EA810870 наполнит дом чудесным ароматом и приготовит для вас бодрящий эспрессо, лунго и ристретто, мягкий латте и капучино, а объёма 1,7 л хватит, чтобы собрать за столом всю семью и гостей – ведь можно делать две порции одновременно.');
INSERT INTO public.product (id, file_name, file_path, file_type, file_size, title, price, description) VALUES (2, '20031953bb2.jpg', 'C:\Users\minya\Documents\Code\Java\attestation-spring-app\uploads\images\20031953bb2.jpg', 'image/jpeg', 151261, 'Кофемашина Krups Lattespress EA829810', 59999.00, 'Кофемашина Krups EA829810 оснащается встроенной кофемолкой и автоматическим капучинатором. Благодаря этому она способна готовить любые напитки за считанные секунды - пользователю достаточно лишь выбрать программу и нажать на соответствующую кнопку.');
INSERT INTO public.product (id, file_name, file_path, file_type, file_size, title, price, description) VALUES (3, '20040705bb3.jpg', 'C:\Users\minya\Documents\Code\Java\attestation-spring-app\uploads\images\20040705bb3.jpg', 'image/jpeg', 157857, 'Кофемашина Krups Quattro Force Evidence EA891810', 69999.00, 'Кофемашина Krups EA891810 оборудована встроенной кофемолкой и автоматическим капучинатором. Она способна готовить ваши любимые напитки за считанные секунды – достаточно лишь выбрать программу и нажать на соответствующую кнопку.');


--
-- TOC entry 3364 (class 0 OID 16418)
-- Dependencies: 221
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."user" (id, username, password, role) VALUES (1, 'admin', '$2a$12$3Dv9kVS3aCJLRa/cpAGUveQm99cmCeHvYZhWDptPhpSx9YjVPdvXS', 'ROLE_ADMIN');
INSERT INTO public."user" (id, username, password, role) VALUES (2, 'user', '$2a$10$YtiLbwEOnvrYYkZ4UQKK3uQ0pQMUdtYW2riOVrDc6niwu/AVaU3e.', 'ROLE_USER');


--
-- TOC entry 3371 (class 0 OID 0)
-- Dependencies: 215
-- Name: cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cart_id_seq', 1, true);


--
-- TOC entry 3372 (class 0 OID 0)
-- Dependencies: 217
-- Name: order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_id_seq', 1, true);


--
-- TOC entry 3373 (class 0 OID 0)
-- Dependencies: 220
-- Name: product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_id_seq', 3, true);


--
-- TOC entry 3374 (class 0 OID 0)
-- Dependencies: 222
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 2, true);


--
-- TOC entry 3195 (class 2606 OID 16423)
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (id);


--
-- TOC entry 3197 (class 2606 OID 16425)
-- Name: order order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_pkey PRIMARY KEY (id);


--
-- TOC entry 3199 (class 2606 OID 16427)
-- Name: orders_products orders_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_products
    ADD CONSTRAINT orders_products_pkey PRIMARY KEY (order_id, product_id);


--
-- TOC entry 3201 (class 2606 OID 16429)
-- Name: product product_file_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_file_name_key UNIQUE (file_name);


--
-- TOC entry 3203 (class 2606 OID 16431)
-- Name: product product_file_path_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_file_path_key UNIQUE (file_path);


--
-- TOC entry 3205 (class 2606 OID 16433)
-- Name: product product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product
    ADD CONSTRAINT product_pkey PRIMARY KEY (id);


--
-- TOC entry 3207 (class 2606 OID 16435)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 3209 (class 2606 OID 16437)
-- Name: user user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_username_key UNIQUE (username);


--
-- TOC entry 3210 (class 2606 OID 16438)
-- Name: cart cart_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id);


--
-- TOC entry 3211 (class 2606 OID 16443)
-- Name: cart cart_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 3212 (class 2606 OID 16448)
-- Name: order order_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."order"
    ADD CONSTRAINT order_user_id_fkey FOREIGN KEY (user_id) REFERENCES public."user"(id);


--
-- TOC entry 3213 (class 2606 OID 16453)
-- Name: orders_products orders_products_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_products
    ADD CONSTRAINT orders_products_order_id_fkey FOREIGN KEY (order_id) REFERENCES public."order"(id);


--
-- TOC entry 3214 (class 2606 OID 16458)
-- Name: orders_products orders_products_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_products
    ADD CONSTRAINT orders_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.product(id);


-- Completed on 2023-05-30 13:59:09

--
-- PostgreSQL database dump complete
--

